// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: breakdown.proto

package de.marketmaker.istar.merger.provider.protobuf;

public final class BreakdownProtos {
  private BreakdownProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BreakdownItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.BreakdownItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    java.util.List<de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString> 
        getNameList();
    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString getName(int index);
    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    int getNameCount();
    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    java.util.List<? extends de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedStringOrBuilder> 
        getNameOrBuilderList();
    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedStringOrBuilder getNameOrBuilder(
        int index);

    /**
     * <code>optional string share = 2;</code>
     */
    boolean hasShare();
    /**
     * <code>optional string share = 2;</code>
     */
    java.lang.String getShare();
    /**
     * <code>optional string share = 2;</code>
     */
    com.google.protobuf.ByteString
        getShareBytes();

    /**
     * <code>optional string type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>optional string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string meta = 4;</code>
     */
    boolean hasMeta();
    /**
     * <code>optional string meta = 4;</code>
     */
    java.lang.String getMeta();
    /**
     * <code>optional string meta = 4;</code>
     */
    com.google.protobuf.ByteString
        getMetaBytes();

    /**
     * <code>optional int32 lastupdate = 5;</code>
     */
    boolean hasLastupdate();
    /**
     * <code>optional int32 lastupdate = 5;</code>
     */
    int getLastupdate();
  }
  /**
   * Protobuf type {@code protobuf.BreakdownItem}
   */
  public static final class BreakdownItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.BreakdownItem)
      BreakdownItemOrBuilder {
    // Use BreakdownItem.newBuilder() to construct.
    private BreakdownItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BreakdownItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BreakdownItem defaultInstance;
    public static BreakdownItem getDefaultInstance() {
      return defaultInstance;
    }

    public BreakdownItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BreakdownItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                name_ = new java.util.ArrayList<de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString>();
                mutable_bitField0_ |= 0x00000001;
              }
              name_.add(input.readMessage(de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              share_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              type_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              meta_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              lastupdate_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = java.util.Collections.unmodifiableList(name_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_BreakdownItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_BreakdownItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.class, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder.class);
    }

    public static com.google.protobuf.Parser<BreakdownItem> PARSER =
        new com.google.protobuf.AbstractParser<BreakdownItem>() {
      public BreakdownItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BreakdownItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BreakdownItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.util.List<de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString> name_;
    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    public java.util.List<de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString> getNameList() {
      return name_;
    }
    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    public java.util.List<? extends de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedStringOrBuilder> 
        getNameOrBuilderList() {
      return name_;
    }
    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    public int getNameCount() {
      return name_.size();
    }
    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    public de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString getName(int index) {
      return name_.get(index);
    }
    /**
     * <code>repeated .protobuf.LocalizedString name = 1;</code>
     */
    public de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedStringOrBuilder getNameOrBuilder(
        int index) {
      return name_.get(index);
    }

    public static final int SHARE_FIELD_NUMBER = 2;
    private java.lang.Object share_;
    /**
     * <code>optional string share = 2;</code>
     */
    public boolean hasShare() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string share = 2;</code>
     */
    public java.lang.String getShare() {
      java.lang.Object ref = share_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          share_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string share = 2;</code>
     */
    public com.google.protobuf.ByteString
        getShareBytes() {
      java.lang.Object ref = share_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        share_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private java.lang.Object type_;
    /**
     * <code>optional string type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int META_FIELD_NUMBER = 4;
    private java.lang.Object meta_;
    /**
     * <code>optional string meta = 4;</code>
     */
    public boolean hasMeta() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string meta = 4;</code>
     */
    public java.lang.String getMeta() {
      java.lang.Object ref = meta_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          meta_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string meta = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMetaBytes() {
      java.lang.Object ref = meta_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        meta_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTUPDATE_FIELD_NUMBER = 5;
    private int lastupdate_;
    /**
     * <code>optional int32 lastupdate = 5;</code>
     */
    public boolean hasLastupdate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 lastupdate = 5;</code>
     */
    public int getLastupdate() {
      return lastupdate_;
    }

    private void initFields() {
      name_ = java.util.Collections.emptyList();
      share_ = "";
      type_ = "";
      meta_ = "";
      lastupdate_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getNameCount(); i++) {
        if (!getName(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < name_.size(); i++) {
        output.writeMessage(1, name_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getShareBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getMetaBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, lastupdate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < name_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, name_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getShareBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMetaBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, lastupdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.BreakdownItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.BreakdownItem)
        de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_BreakdownItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_BreakdownItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.class, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder.class);
      }

      // Construct using de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNameFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (nameBuilder_ == null) {
          name_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nameBuilder_.clear();
        }
        share_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        meta_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        lastupdate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_BreakdownItem_descriptor;
      }

      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem getDefaultInstanceForType() {
        return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.getDefaultInstance();
      }

      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem build() {
        de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem buildPartial() {
        de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem result = new de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (nameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            name_ = java.util.Collections.unmodifiableList(name_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.name_ = name_;
        } else {
          result.name_ = nameBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.share_ = share_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.meta_ = meta_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastupdate_ = lastupdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem) {
          return mergeFrom((de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem other) {
        if (other == de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.getDefaultInstance()) return this;
        if (nameBuilder_ == null) {
          if (!other.name_.isEmpty()) {
            if (name_.isEmpty()) {
              name_ = other.name_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNameIsMutable();
              name_.addAll(other.name_);
            }
            onChanged();
          }
        } else {
          if (!other.name_.isEmpty()) {
            if (nameBuilder_.isEmpty()) {
              nameBuilder_.dispose();
              nameBuilder_ = null;
              name_ = other.name_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nameBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNameFieldBuilder() : null;
            } else {
              nameBuilder_.addAllMessages(other.name_);
            }
          }
        }
        if (other.hasShare()) {
          bitField0_ |= 0x00000002;
          share_ = other.share_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasMeta()) {
          bitField0_ |= 0x00000008;
          meta_ = other.meta_;
          onChanged();
        }
        if (other.hasLastupdate()) {
          setLastupdate(other.getLastupdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getNameCount(); i++) {
          if (!getName(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString> name_ =
        java.util.Collections.emptyList();
      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = new java.util.ArrayList<de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString>(name_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedStringOrBuilder> nameBuilder_;

      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public java.util.List<de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString> getNameList() {
        if (nameBuilder_ == null) {
          return java.util.Collections.unmodifiableList(name_);
        } else {
          return nameBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public int getNameCount() {
        if (nameBuilder_ == null) {
          return name_.size();
        } else {
          return nameBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString getName(int index) {
        if (nameBuilder_ == null) {
          return name_.get(index);
        } else {
          return nameBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public Builder setName(
          int index, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNameIsMutable();
          name_.set(index, value);
          onChanged();
        } else {
          nameBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public Builder setName(
          int index, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder builderForValue) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          name_.set(index, builderForValue.build());
          onChanged();
        } else {
          nameBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public Builder addName(de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNameIsMutable();
          name_.add(value);
          onChanged();
        } else {
          nameBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public Builder addName(
          int index, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNameIsMutable();
          name_.add(index, value);
          onChanged();
        } else {
          nameBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public Builder addName(
          de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder builderForValue) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          name_.add(builderForValue.build());
          onChanged();
        } else {
          nameBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public Builder addName(
          int index, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder builderForValue) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          name_.add(index, builderForValue.build());
          onChanged();
        } else {
          nameBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public Builder addAllName(
          java.lang.Iterable<? extends de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString> values) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, name_);
          onChanged();
        } else {
          nameBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public Builder clearName() {
        if (nameBuilder_ == null) {
          name_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nameBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public Builder removeName(int index) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          name_.remove(index);
          onChanged();
        } else {
          nameBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder getNameBuilder(
          int index) {
        return getNameFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedStringOrBuilder getNameOrBuilder(
          int index) {
        if (nameBuilder_ == null) {
          return name_.get(index);  } else {
          return nameBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public java.util.List<? extends de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedStringOrBuilder> 
           getNameOrBuilderList() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(name_);
        }
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder addNameBuilder() {
        return getNameFieldBuilder().addBuilder(
            de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder addNameBuilder(
          int index) {
        return getNameFieldBuilder().addBuilder(
            index, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.LocalizedString name = 1;</code>
       */
      public java.util.List<de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder> 
           getNameBuilderList() {
        return getNameFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedStringOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedString.Builder, de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.LocalizedStringOrBuilder>(
                  name_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }

      private java.lang.Object share_ = "";
      /**
       * <code>optional string share = 2;</code>
       */
      public boolean hasShare() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string share = 2;</code>
       */
      public java.lang.String getShare() {
        java.lang.Object ref = share_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            share_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string share = 2;</code>
       */
      public com.google.protobuf.ByteString
          getShareBytes() {
        java.lang.Object ref = share_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          share_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string share = 2;</code>
       */
      public Builder setShare(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        share_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string share = 2;</code>
       */
      public Builder clearShare() {
        bitField0_ = (bitField0_ & ~0x00000002);
        share_ = getDefaultInstance().getShare();
        onChanged();
        return this;
      }
      /**
       * <code>optional string share = 2;</code>
       */
      public Builder setShareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        share_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object meta_ = "";
      /**
       * <code>optional string meta = 4;</code>
       */
      public boolean hasMeta() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string meta = 4;</code>
       */
      public java.lang.String getMeta() {
        java.lang.Object ref = meta_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            meta_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string meta = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMetaBytes() {
        java.lang.Object ref = meta_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          meta_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string meta = 4;</code>
       */
      public Builder setMeta(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        meta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string meta = 4;</code>
       */
      public Builder clearMeta() {
        bitField0_ = (bitField0_ & ~0x00000008);
        meta_ = getDefaultInstance().getMeta();
        onChanged();
        return this;
      }
      /**
       * <code>optional string meta = 4;</code>
       */
      public Builder setMetaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        meta_ = value;
        onChanged();
        return this;
      }

      private int lastupdate_ ;
      /**
       * <code>optional int32 lastupdate = 5;</code>
       */
      public boolean hasLastupdate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 lastupdate = 5;</code>
       */
      public int getLastupdate() {
        return lastupdate_;
      }
      /**
       * <code>optional int32 lastupdate = 5;</code>
       */
      public Builder setLastupdate(int value) {
        bitField0_ |= 0x00000010;
        lastupdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lastupdate = 5;</code>
       */
      public Builder clearLastupdate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastupdate_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.BreakdownItem)
    }

    static {
      defaultInstance = new BreakdownItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.BreakdownItem)
  }

  public interface BreakdownOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Breakdown)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 security = 1;</code>
     */
    boolean hasSecurity();
    /**
     * <code>required int64 security = 1;</code>
     */
    long getSecurity();

    /**
     * <code>optional string msmarketAdmission = 2;</code>
     */
    boolean hasMsmarketAdmission();
    /**
     * <code>optional string msmarketAdmission = 2;</code>
     */
    java.lang.String getMsmarketAdmission();
    /**
     * <code>optional string msmarketAdmission = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsmarketAdmissionBytes();

    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    java.util.List<de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem> 
        getItemsList();
    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem getItems(int index);
    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    java.util.List<? extends de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.Breakdown}
   */
  public static final class Breakdown extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.Breakdown)
      BreakdownOrBuilder {
    // Use Breakdown.newBuilder() to construct.
    private Breakdown(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Breakdown(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Breakdown defaultInstance;
    public static Breakdown getDefaultInstance() {
      return defaultInstance;
    }

    public Breakdown getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Breakdown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              security_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              msmarketAdmission_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                items_ = new java.util.ArrayList<de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem>();
                mutable_bitField0_ |= 0x00000004;
              }
              items_.add(input.readMessage(de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_Breakdown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_Breakdown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown.class, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown.Builder.class);
    }

    public static com.google.protobuf.Parser<Breakdown> PARSER =
        new com.google.protobuf.AbstractParser<Breakdown>() {
      public Breakdown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Breakdown(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Breakdown> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SECURITY_FIELD_NUMBER = 1;
    private long security_;
    /**
     * <code>required int64 security = 1;</code>
     */
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 security = 1;</code>
     */
    public long getSecurity() {
      return security_;
    }

    public static final int MSMARKETADMISSION_FIELD_NUMBER = 2;
    private java.lang.Object msmarketAdmission_;
    /**
     * <code>optional string msmarketAdmission = 2;</code>
     */
    public boolean hasMsmarketAdmission() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msmarketAdmission = 2;</code>
     */
    public java.lang.String getMsmarketAdmission() {
      java.lang.Object ref = msmarketAdmission_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msmarketAdmission_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msmarketAdmission = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsmarketAdmissionBytes() {
      java.lang.Object ref = msmarketAdmission_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msmarketAdmission_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITEMS_FIELD_NUMBER = 3;
    private java.util.List<de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem> items_;
    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    public java.util.List<de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    public java.util.List<? extends de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .protobuf.BreakdownItem items = 3;</code>
     */
    public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      security_ = 0L;
      msmarketAdmission_ = "";
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSecurity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, security_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsmarketAdmissionBytes());
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(3, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, security_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsmarketAdmissionBytes());
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Breakdown}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Breakdown)
        de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_Breakdown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_Breakdown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown.class, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown.Builder.class);
      }

      // Construct using de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        security_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        msmarketAdmission_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.internal_static_protobuf_Breakdown_descriptor;
      }

      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown getDefaultInstanceForType() {
        return de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown.getDefaultInstance();
      }

      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown build() {
        de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown buildPartial() {
        de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown result = new de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.security_ = security_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msmarketAdmission_ = msmarketAdmission_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown) {
          return mergeFrom((de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown other) {
        if (other == de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown.getDefaultInstance()) return this;
        if (other.hasSecurity()) {
          setSecurity(other.getSecurity());
        }
        if (other.hasMsmarketAdmission()) {
          bitField0_ |= 0x00000002;
          msmarketAdmission_ = other.msmarketAdmission_;
          onChanged();
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000004);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSecurity()) {
          
          return false;
        }
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.Breakdown) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long security_ ;
      /**
       * <code>required int64 security = 1;</code>
       */
      public boolean hasSecurity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 security = 1;</code>
       */
      public long getSecurity() {
        return security_;
      }
      /**
       * <code>required int64 security = 1;</code>
       */
      public Builder setSecurity(long value) {
        bitField0_ |= 0x00000001;
        security_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 security = 1;</code>
       */
      public Builder clearSecurity() {
        bitField0_ = (bitField0_ & ~0x00000001);
        security_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msmarketAdmission_ = "";
      /**
       * <code>optional string msmarketAdmission = 2;</code>
       */
      public boolean hasMsmarketAdmission() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msmarketAdmission = 2;</code>
       */
      public java.lang.String getMsmarketAdmission() {
        java.lang.Object ref = msmarketAdmission_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msmarketAdmission_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msmarketAdmission = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsmarketAdmissionBytes() {
        java.lang.Object ref = msmarketAdmission_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msmarketAdmission_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msmarketAdmission = 2;</code>
       */
      public Builder setMsmarketAdmission(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msmarketAdmission_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msmarketAdmission = 2;</code>
       */
      public Builder clearMsmarketAdmission() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msmarketAdmission_ = getDefaultInstance().getMsmarketAdmission();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msmarketAdmission = 2;</code>
       */
      public Builder setMsmarketAdmissionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msmarketAdmission_ = value;
        onChanged();
        return this;
      }

      private java.util.List<de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          items_ = new java.util.ArrayList<de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem>(items_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public java.util.List<de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public Builder setItems(
          int index, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public Builder setItems(
          int index, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public Builder addItems(de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public Builder addItems(
          int index, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public Builder addItems(
          de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public Builder addItems(
          int index, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public java.util.List<? extends de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.BreakdownItem items = 3;</code>
       */
      public java.util.List<de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItem.Builder, de.marketmaker.istar.merger.provider.protobuf.BreakdownProtos.BreakdownItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Breakdown)
    }

    static {
      defaultInstance = new Breakdown(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Breakdown)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_BreakdownItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_BreakdownItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Breakdown_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Breakdown_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017breakdown.proto\022\010protobuf\032 google/prot" +
      "obuf/descriptor.proto\032\016provider.proto\"\211\001" +
      "\n\rBreakdownItem\022-\n\004name\030\001 \003(\0132\031.protobuf" +
      ".LocalizedStringB\004\230\202\031\001\022\r\n\005share\030\002 \001(\t\022\022\n" +
      "\004type\030\003 \001(\tB\004\230\202\031\001\022\014\n\004meta\030\004 \001(\t\022\030\n\nlastu" +
      "pdate\030\005 \001(\005B\004\220\202\031\002\"f\n\tBreakdown\022\020\n\010securi" +
      "ty\030\001 \002(\003\022\037\n\021msmarketAdmission\030\002 \001(\tB\004\230\202\031" +
      "\001\022&\n\005items\030\003 \003(\0132\027.protobuf.BreakdownIte" +
      "mBB\n-de.marketmaker.istar.merger.provide" +
      "r.protobufB\017BreakdownProtosH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.getDescriptor(),
        }, assigner);
    internal_static_protobuf_BreakdownItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_BreakdownItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_BreakdownItem_descriptor,
        new java.lang.String[] { "Name", "Share", "Type", "Meta", "Lastupdate", });
    internal_static_protobuf_Breakdown_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_Breakdown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_Breakdown_descriptor,
        new java.lang.String[] { "Security", "MsmarketAdmission", "Items", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.cachedStringOption);
    registry.add(de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.cachedStringOption);
    registry.add(de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.wmTypeOption);
    registry.add(de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.cachedStringOption);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
    de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
