// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating_history.proto

package de.marketmaker.istar.merger.provider.protobuf;

public final class RatingHistoryProtos {
  private RatingHistoryProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RatingHistoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.RatingHistory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 iid = 1;</code>
     */
    boolean hasIid();
    /**
     * <code>required int64 iid = 1;</code>
     */
    long getIid();

    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    java.util.List<de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem> 
        getRatingsList();
    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem getRatings(int index);
    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    int getRatingsCount();
    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    java.util.List<? extends de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder> 
        getRatingsOrBuilderList();
    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder getRatingsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.RatingHistory}
   */
  public static final class RatingHistory extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.RatingHistory)
      RatingHistoryOrBuilder {
    // Use RatingHistory.newBuilder() to construct.
    private RatingHistory(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RatingHistory(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RatingHistory defaultInstance;
    public static RatingHistory getDefaultInstance() {
      return defaultInstance;
    }

    public RatingHistory getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RatingHistory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              iid_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                ratings_ = new java.util.ArrayList<de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              ratings_.add(input.readMessage(de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          ratings_ = java.util.Collections.unmodifiableList(ratings_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingHistory_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingHistory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory.class, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory.Builder.class);
    }

    public static com.google.protobuf.Parser<RatingHistory> PARSER =
        new com.google.protobuf.AbstractParser<RatingHistory>() {
      public RatingHistory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RatingHistory(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RatingHistory> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IID_FIELD_NUMBER = 1;
    private long iid_;
    /**
     * <code>required int64 iid = 1;</code>
     */
    public boolean hasIid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 iid = 1;</code>
     */
    public long getIid() {
      return iid_;
    }

    public static final int RATINGS_FIELD_NUMBER = 2;
    private java.util.List<de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem> ratings_;
    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    public java.util.List<de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem> getRatingsList() {
      return ratings_;
    }
    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    public java.util.List<? extends de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder> 
        getRatingsOrBuilderList() {
      return ratings_;
    }
    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    public int getRatingsCount() {
      return ratings_.size();
    }
    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem getRatings(int index) {
      return ratings_.get(index);
    }
    /**
     * <code>repeated .protobuf.RatingItem ratings = 2;</code>
     */
    public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder getRatingsOrBuilder(
        int index) {
      return ratings_.get(index);
    }

    private void initFields() {
      iid_ = 0L;
      ratings_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, iid_);
      }
      for (int i = 0; i < ratings_.size(); i++) {
        output.writeMessage(2, ratings_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, iid_);
      }
      for (int i = 0; i < ratings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, ratings_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.RatingHistory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.RatingHistory)
        de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingHistory_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingHistory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory.class, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory.Builder.class);
      }

      // Construct using de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRatingsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        iid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (ratingsBuilder_ == null) {
          ratings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ratingsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingHistory_descriptor;
      }

      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory getDefaultInstanceForType() {
        return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory.getDefaultInstance();
      }

      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory build() {
        de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory buildPartial() {
        de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory result = new de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iid_ = iid_;
        if (ratingsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            ratings_ = java.util.Collections.unmodifiableList(ratings_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.ratings_ = ratings_;
        } else {
          result.ratings_ = ratingsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory) {
          return mergeFrom((de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory other) {
        if (other == de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory.getDefaultInstance()) return this;
        if (other.hasIid()) {
          setIid(other.getIid());
        }
        if (ratingsBuilder_ == null) {
          if (!other.ratings_.isEmpty()) {
            if (ratings_.isEmpty()) {
              ratings_ = other.ratings_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRatingsIsMutable();
              ratings_.addAll(other.ratings_);
            }
            onChanged();
          }
        } else {
          if (!other.ratings_.isEmpty()) {
            if (ratingsBuilder_.isEmpty()) {
              ratingsBuilder_.dispose();
              ratingsBuilder_ = null;
              ratings_ = other.ratings_;
              bitField0_ = (bitField0_ & ~0x00000002);
              ratingsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRatingsFieldBuilder() : null;
            } else {
              ratingsBuilder_.addAllMessages(other.ratings_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingHistory) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long iid_ ;
      /**
       * <code>required int64 iid = 1;</code>
       */
      public boolean hasIid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 iid = 1;</code>
       */
      public long getIid() {
        return iid_;
      }
      /**
       * <code>required int64 iid = 1;</code>
       */
      public Builder setIid(long value) {
        bitField0_ |= 0x00000001;
        iid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 iid = 1;</code>
       */
      public Builder clearIid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iid_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem> ratings_ =
        java.util.Collections.emptyList();
      private void ensureRatingsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          ratings_ = new java.util.ArrayList<de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem>(ratings_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder> ratingsBuilder_;

      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public java.util.List<de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem> getRatingsList() {
        if (ratingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ratings_);
        } else {
          return ratingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public int getRatingsCount() {
        if (ratingsBuilder_ == null) {
          return ratings_.size();
        } else {
          return ratingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem getRatings(int index) {
        if (ratingsBuilder_ == null) {
          return ratings_.get(index);
        } else {
          return ratingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public Builder setRatings(
          int index, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem value) {
        if (ratingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatingsIsMutable();
          ratings_.set(index, value);
          onChanged();
        } else {
          ratingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public Builder setRatings(
          int index, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder builderForValue) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          ratings_.set(index, builderForValue.build());
          onChanged();
        } else {
          ratingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public Builder addRatings(de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem value) {
        if (ratingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatingsIsMutable();
          ratings_.add(value);
          onChanged();
        } else {
          ratingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public Builder addRatings(
          int index, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem value) {
        if (ratingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatingsIsMutable();
          ratings_.add(index, value);
          onChanged();
        } else {
          ratingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public Builder addRatings(
          de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder builderForValue) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          ratings_.add(builderForValue.build());
          onChanged();
        } else {
          ratingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public Builder addRatings(
          int index, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder builderForValue) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          ratings_.add(index, builderForValue.build());
          onChanged();
        } else {
          ratingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public Builder addAllRatings(
          java.lang.Iterable<? extends de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem> values) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ratings_);
          onChanged();
        } else {
          ratingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public Builder clearRatings() {
        if (ratingsBuilder_ == null) {
          ratings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          ratingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public Builder removeRatings(int index) {
        if (ratingsBuilder_ == null) {
          ensureRatingsIsMutable();
          ratings_.remove(index);
          onChanged();
        } else {
          ratingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder getRatingsBuilder(
          int index) {
        return getRatingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder getRatingsOrBuilder(
          int index) {
        if (ratingsBuilder_ == null) {
          return ratings_.get(index);  } else {
          return ratingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public java.util.List<? extends de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder> 
           getRatingsOrBuilderList() {
        if (ratingsBuilder_ != null) {
          return ratingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ratings_);
        }
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder addRatingsBuilder() {
        return getRatingsFieldBuilder().addBuilder(
            de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder addRatingsBuilder(
          int index) {
        return getRatingsFieldBuilder().addBuilder(
            index, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.RatingItem ratings = 2;</code>
       */
      public java.util.List<de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder> 
           getRatingsBuilderList() {
        return getRatingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder> 
          getRatingsFieldBuilder() {
        if (ratingsBuilder_ == null) {
          ratingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder>(
                  ratings_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          ratings_ = null;
        }
        return ratingsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.RatingHistory)
    }

    static {
      defaultInstance = new RatingHistory(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.RatingHistory)
  }

  public interface RatingItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.RatingItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 rating_date = 1;</code>
     */
    boolean hasRatingDate();
    /**
     * <code>optional int32 rating_date = 1;</code>
     */
    int getRatingDate();

    /**
     * <code>optional string rating_value = 2;</code>
     */
    boolean hasRatingValue();
    /**
     * <code>optional string rating_value = 2;</code>
     */
    java.lang.String getRatingValue();
    /**
     * <code>optional string rating_value = 2;</code>
     */
    com.google.protobuf.ByteString
        getRatingValueBytes();

    /**
     * <code>optional string rating_type = 3;</code>
     */
    boolean hasRatingType();
    /**
     * <code>optional string rating_type = 3;</code>
     */
    java.lang.String getRatingType();
    /**
     * <code>optional string rating_type = 3;</code>
     */
    com.google.protobuf.ByteString
        getRatingTypeBytes();
  }
  /**
   * Protobuf type {@code protobuf.RatingItem}
   */
  public static final class RatingItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.RatingItem)
      RatingItemOrBuilder {
    // Use RatingItem.newBuilder() to construct.
    private RatingItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RatingItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RatingItem defaultInstance;
    public static RatingItem getDefaultInstance() {
      return defaultInstance;
    }

    public RatingItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RatingItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ratingDate_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ratingValue_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              ratingType_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.class, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder.class);
    }

    public static com.google.protobuf.Parser<RatingItem> PARSER =
        new com.google.protobuf.AbstractParser<RatingItem>() {
      public RatingItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RatingItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RatingItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RATING_DATE_FIELD_NUMBER = 1;
    private int ratingDate_;
    /**
     * <code>optional int32 rating_date = 1;</code>
     */
    public boolean hasRatingDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 rating_date = 1;</code>
     */
    public int getRatingDate() {
      return ratingDate_;
    }

    public static final int RATING_VALUE_FIELD_NUMBER = 2;
    private java.lang.Object ratingValue_;
    /**
     * <code>optional string rating_value = 2;</code>
     */
    public boolean hasRatingValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string rating_value = 2;</code>
     */
    public java.lang.String getRatingValue() {
      java.lang.Object ref = ratingValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ratingValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rating_value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRatingValueBytes() {
      java.lang.Object ref = ratingValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ratingValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RATING_TYPE_FIELD_NUMBER = 3;
    private java.lang.Object ratingType_;
    /**
     * <code>optional string rating_type = 3;</code>
     */
    public boolean hasRatingType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string rating_type = 3;</code>
     */
    public java.lang.String getRatingType() {
      java.lang.Object ref = ratingType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ratingType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rating_type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRatingTypeBytes() {
      java.lang.Object ref = ratingType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ratingType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ratingDate_ = 0;
      ratingValue_ = "";
      ratingType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ratingDate_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRatingValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRatingTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ratingDate_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRatingValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRatingTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.RatingItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.RatingItem)
        de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.class, de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.Builder.class);
      }

      // Construct using de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ratingDate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ratingValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ratingType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.internal_static_protobuf_RatingItem_descriptor;
      }

      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem getDefaultInstanceForType() {
        return de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.getDefaultInstance();
      }

      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem build() {
        de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem buildPartial() {
        de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem result = new de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ratingDate_ = ratingDate_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ratingValue_ = ratingValue_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ratingType_ = ratingType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem) {
          return mergeFrom((de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem other) {
        if (other == de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem.getDefaultInstance()) return this;
        if (other.hasRatingDate()) {
          setRatingDate(other.getRatingDate());
        }
        if (other.hasRatingValue()) {
          bitField0_ |= 0x00000002;
          ratingValue_ = other.ratingValue_;
          onChanged();
        }
        if (other.hasRatingType()) {
          bitField0_ |= 0x00000004;
          ratingType_ = other.ratingType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.marketmaker.istar.merger.provider.protobuf.RatingHistoryProtos.RatingItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ratingDate_ ;
      /**
       * <code>optional int32 rating_date = 1;</code>
       */
      public boolean hasRatingDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 rating_date = 1;</code>
       */
      public int getRatingDate() {
        return ratingDate_;
      }
      /**
       * <code>optional int32 rating_date = 1;</code>
       */
      public Builder setRatingDate(int value) {
        bitField0_ |= 0x00000001;
        ratingDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rating_date = 1;</code>
       */
      public Builder clearRatingDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ratingDate_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ratingValue_ = "";
      /**
       * <code>optional string rating_value = 2;</code>
       */
      public boolean hasRatingValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string rating_value = 2;</code>
       */
      public java.lang.String getRatingValue() {
        java.lang.Object ref = ratingValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ratingValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rating_value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRatingValueBytes() {
        java.lang.Object ref = ratingValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ratingValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rating_value = 2;</code>
       */
      public Builder setRatingValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ratingValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rating_value = 2;</code>
       */
      public Builder clearRatingValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ratingValue_ = getDefaultInstance().getRatingValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rating_value = 2;</code>
       */
      public Builder setRatingValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ratingValue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ratingType_ = "";
      /**
       * <code>optional string rating_type = 3;</code>
       */
      public boolean hasRatingType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string rating_type = 3;</code>
       */
      public java.lang.String getRatingType() {
        java.lang.Object ref = ratingType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ratingType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rating_type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRatingTypeBytes() {
        java.lang.Object ref = ratingType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ratingType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rating_type = 3;</code>
       */
      public Builder setRatingType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ratingType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rating_type = 3;</code>
       */
      public Builder clearRatingType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ratingType_ = getDefaultInstance().getRatingType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rating_type = 3;</code>
       */
      public Builder setRatingTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ratingType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.RatingItem)
    }

    static {
      defaultInstance = new RatingItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.RatingItem)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_RatingHistory_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_RatingHistory_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_RatingItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_RatingItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024rating_history.proto\022\010protobuf\032 google" +
      "/protobuf/descriptor.proto\032\016provider.pro" +
      "to\"C\n\rRatingHistory\022\013\n\003iid\030\001 \002(\003\022%\n\007rati" +
      "ngs\030\002 \003(\0132\024.protobuf.RatingItem\"^\n\nRatin" +
      "gItem\022\031\n\013rating_date\030\001 \001(\005B\004\220\202\031\002\022\032\n\014rati" +
      "ng_value\030\002 \001(\tB\004\230\202\031\001\022\031\n\013rating_type\030\003 \001(" +
      "\tB\004\230\202\031\001BF\n-de.marketmaker.istar.merger.p" +
      "rovider.protobufB\023RatingHistoryProtosH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.getDescriptor(),
        }, assigner);
    internal_static_protobuf_RatingHistory_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_RatingHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_RatingHistory_descriptor,
        new java.lang.String[] { "Iid", "Ratings", });
    internal_static_protobuf_RatingItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_RatingItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_RatingItem_descriptor,
        new java.lang.String[] { "RatingDate", "RatingValue", "RatingType", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.wmTypeOption);
    registry.add(de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.cachedStringOption);
    registry.add(de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.cachedStringOption);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
    de.marketmaker.istar.merger.provider.protobuf.ProviderProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
