/*
 * Selector.java
 *
 * Created on 10.09.2008 10:38:55
 *
 * Copyright (c) market maker Software AG. All Rights Reserved.
 */
package de.marketmaker.istar.domain.profile;

import java.util.Arrays;

import static de.marketmaker.istar.domain.profile.Profile.Aspect.*;

/**
 * @author Oliver Flege
 * @author Thomas Kiesgen
 */
public enum Selector {
    OPRA(151 /*EntitlementsVwd.toValue("6U")*/, PRICE),
    FUNDDATA_MORNINGSTAR_DE(196, PRICE),
    SCREENER(210, FUNCTION),
    CONVENSYS_I(211, FUNCTION, "B"),
    CONVENSYS_II(212, FUNCTION),
    FERI(213, FUNCTION),
    FITCH_CDS(214, PRICE),
    DZBANK_USER_MESSAGES(223, NEWS),
    FUNDDATA_VWD_IT(229, PRICE),
    FACTSET(244, PRICE),
    VOLA_INDIZES(338, PRICE),
    XRATE(347, PRICE),
    TULLET(381, PRICE),
    EUREX_FUTURES(394, PRICE),
    EUREX_OPTIONS(395, PRICE),
    RATING_FITCH(396, PRICE),
    RATING_MOODYS(414, PRICE),
    SMF_STATIC_DATA(513, PRICE),
    SMF_RATIO_DATA(514, PRICE),
    DZBANK_WEB_INVESTOR(2003, PRODUCT),
    DZBANK_WEB_INFORMER(2004, PRODUCT),
    RATING_MORNINGSTAR(2007, FUNCTION),
    UNION_PIFS(2008, FUNCTION),
    ATTRAX(2009, FUNCTION),
    PAGES_DZBANK(2010, FUNCTION),
    VALOR_DATA_BROWSER(2016, FUNCTION),
    NEWS_DPA(2018, FUNCTION),
    PLATOW(2020, FUNCTION),
    NEWS_REUTERS(2022, FUNCTION),
    SMARTHOUSE_ANALYSES(2023, FUNCTION),
    PROFIT_ESTIMATES_AND_PER(2024, FUNCTION),
    TIMES_AND_SALES(2025, FUNCTION),
    HISTORICAL_PERFORMANCE(2029, FUNCTION),
    FINDER_ANALYSIS(2034, FUNCTION),
    PAGES_VWD(2038, Profile.Aspect.PAGE),
    MY_WORKSPACE_ADVANCED(2047, FUNCTION),
    WARRANT_CALCULATOR(2048, FUNCTION),
    BOND_CALCULATOR(2049, FUNCTION),
    KWT(2057, PRODUCT),
    FINDER_EUREX(2059, FUNCTION),
    YIELD_STRUCTURE(2063, FUNCTION),
    WEB_XL(2065, FUNCTION),
    NEWS_NO_ADS(2066, FUNCTION),
    DZ_BANK_USER(2075, FUNCTION),
    WGZ_BANK_USER(2076, FUNCTION),
    SON_BANK_USER(2077, FUNCTION),
    DZ_CER_IPO_MATRIX(2083, FUNCTION),
    TICKER(2086, FUNCTION),
    SEND_NEWS_MAIL(2095, FUNCTION),
    FLEX_CHART(2097, FUNCTION),
    EDG_RATING(2119, FUNCTION),
    VWD_BREAKDOWN(2120, FUNCTION),
    GENOBROKER_BASIC(2139, PRODUCT),
    GENOBROKER_EXTENDED(2140, PRODUCT),
    GENOBROKER_PBL(2141, PRODUCT),
    VRBP_EXTENDED(2145, PRODUCT),
    FUNDDATA_FWW(2177, PRICE, FUNCTION),
    METALS_MOBILE(2204, FUNCTION),
    DOCMAN_SIGNED_PDF(2209, FUNCTION),
    DOCMAN_PDF_A_1B_Format(2210, FUNCTION),
    SOFTWARESYSTEMS_AT_REPORTS_KIID(2211, PRICE, FUNCTION),
    VWD_IT_COMPANY_PROFILES(2224, FUNCTION),
    FACTSET_ESTIMATES_FOR_BOERSE_GO(2231, FUNCTION),
    MARKETMANAGER_PROFILE(2238, FUNCTION),
    ANY_VWD_TERMINAL_PROFILE(2239, FUNCTION),  // used for entitlement of WM data, any means at least mmf or mmf[web]
    PRODUCTALTERNATIVES(2253, FUNCTION),
    MMWEB2_DISABLE_LOGIN(2258, FUNCTION),   // used to disable logins to mmweb2 after switching the customer to mmweb3
    PRODUCT_WITH_PIB(2268, FUNCTION),
    DZ_KAPITALKMARKT(2269, FUNCTION),
    KIID_ARCHIVE(2281, FUNCTION),
    EXCEL_WEB_QUERY_EXPORT(2287, FUNCTION),
    DATA_MANAGER_TREASURY(2299, PRODUCT),
    DOCM_EDIT_ADM(2313, FUNCTION), // document manager: admin edit for text section allowed
    DOCM_EDIT_USER(2314, FUNCTION), // document manager: user edit for text section allowed
    DZ_WERTENTICKLUNGSRECHNER(2397, FUNCTION),
    DZ_RESEARCH(2398, FUNCTION),
    DZ_HM1(2403, FUNCTION),
    DZ_HM2(2404, FUNCTION),
    DZ_HM3(2405, FUNCTION),
    DZ_FP4(2406, FUNCTION),
    DOCM_VENDOR_PIB(2468, FUNCTION), // document manager: upload & management of vendor-specific PIBs allowed
    TICK_DATA_FULL_ACCESS(2472, FUNCTION),
    DOCM_PRIIP_PRODUCT_MANAGEMENT(2484, FUNCTION),
    DOCM_PRIIP_LEGAL_COMPLIANCE(2485, FUNCTION),
    DOCM_PRIIP_SERVICE_PROVIDER(2486, FUNCTION),
    LBBW_RESEARCH(2510, FUNCTION),
    DOCM_PRIIP_RELEASE_MANAGER(2512, FUNCTION),
    DOCM_PRIIP_SERVICE_PROVIDER_ANALYSIS(2523, FUNCTION),
    DOCM_PRIIP_SERVICE_PROVIDER_IMPLEMENTOR(2524, FUNCTION),
    DOCM_ASSET_STOCK(2535, FUNCTION),
    DOCM_ASSET_BONDS(2536, FUNCTION),
    DOCM_PRIIP_APPLICATIONS_SUPPORT(2557, FUNCTION),
    AFU_COMPANY_DATA(2720, FUNCTION),
    VWL_EMERGING_MARKETS(3001, PRICE),
    SHM_ANALYSES(3004, NEWS),
    THOMSONREUTERS_ESTIMATES_DZBANK(3006, PRICE),
    RATING_FERI(3007, PRICE),
    DZB_ITRAXX(3010, PRICE),
    STOCKSELECTION_FUND_REPORTS_DE(3020, PRICE),
    FWW_FUND_REPORTS(3022, PRICE, "3", "WBxFW"),
    STOCKSELECTION_CERTIFICATE_REPORTS(3023, PRICE),
    DZBANK_CERTIFICATE_REPORTS(3026, PRICE),
    FUNDINFO_REPORTS(3044, PRICE),
    EDG_DATA(3047, PRICE), // TODO: remove after 2014-10-24
    EDG_DATA_2(4260, PRICE),
    SOFTWARESYSTEMS_AT_REPORTS(3068, PRICE),
    FUNDDATA_VWD_BENL(3069, PRICE), // removed since 2018-06-13
    DPA_AFX_ANALYSES(3082, NEWS),
    COMPANYDATA_VWD_BENL(3083, FUNCTION),
    FUNDDATA_MORNINGSTAR_CH(3085, PRICE),
    FUNDDATA_MORNINGSTAR_IT(3086, PRICE),
    FUNDDATA_MORNINGSTAR_AT(3087, PRICE),
    STOCKSELECTION_FUND_REPORTS_CH(3088, PRICE),
    STOCKSELECTION_FUND_REPORTS_IT(3089, PRICE),
    STOCKSELECTION_FUND_REPORTS_AT(3090, PRICE),
    FACUNDA_COMPANY_DATA(3362, PRICE),
    FACUNDA_COMPANY_DATA_BOERSE_GO(3363, PRICE),
    IL_SOLE_COMPANY_DATA_PDF(3364, PRICE),
    IL_SOLE_COMPANY_DATA_XML(3365, PRICE),
    ECONODAY(3439, PRICE),
    WEB_SIM_ANALYSES(3440, PRICE),
    SOFTWARESYSTEMS_AT_FACTSHEETS(3454, PRICE),
    RATING_SuP(3455, PRICE),
    OCTOPUS_DATA(3383, PRICE),
    SSAT_FUND_DATA(3456, PRICE),
    FIDA_FUND_DATA(4136, PRICE),
    FIDA_FUND_RATING(4137, PRICE),
    FIDA_FUND_REPORTS_KIID(4138, PRICE),
    FUNDINFO_FACTSHEET(4140, PRICE),
    DOCMAN_CERT_BAYERNLB(4153, PRICE),
    DOCMAN_CERT_BNP(4154, PRICE),
    DOCMAN_CERT_COMMERZBANK(4155, PRICE),
    DOCMAN_CERT_DEUTSCHEBANK(4156, PRICE),
    DOCMAN_CERT_DZBANK(4157, PRICE),
    DOCMAN_CERT_GOLDMAN(4158, PRICE),
    DOCMAN_CERT_SOCGEN(4159, PRICE),
    DOCMAN_CERT_VONTOBEL(4160, PRICE),
    DOCMAN_CERT_UBS(4161, PRICE),
    DOCMAN_CERT_XETRA_GOLD(4168, PRICE),
    DOCMAN_BOND_IKB(4170, PRICE),
    FIDA_FUND_DATA_I(4208, PRICE),
    FIDA_FUND_RATING_I(4209, PRICE),
    DOCMAN_CERT_HSBC(4210, PRICE),
    FIDA_FUND_REPORTS_KIID_I(4211, PRICE),// ISTAR-526
    DOCMAN_CERT_CITIGROUP(4293, PRICE),
    VWD_FUND_DATA(4410, PRICE),
    VWD_FUND_REPORTS(4411, PRICE),
    VWD_FUND_REPORTS_KIID(4412, PRICE),
    VWD_FUND_MAPBIT_BREAKDOWNS(4435, PRICE),
    RATING_MORNINGSTAR_UNION_FND(4443, PRICE),
    SP_GICS_DIRECT(4470, PRICE),
    AWP_ANALYSER(4542, NEWS),
    DIAMOND_RATING(4553, PRICE),
    LBBW_RESEARCH_RESTRICTED_REPORTS(4677, PRICE),
    LBBW_RESEARCH_MAERKTE_IM_BLICK(4678, PRICE),
    DOCMAN_CERT_HVB(4702, PRICE),
    FACUNDA_COMPANY_CALENDAR(4735, PRICE),
    HISTORICAL_EOD_DATA_INDICES_FTSE_MY(5043, PRICE),
    HISTORICAL_EOD_DATA_INDICES_IT(5044, PRICE),
    HISTORICAL_EOD_DATA_INDICES_SIP(5045, PRICE),
    HISTORICAL_EOD_DATA_INDICES_JB(5046, PRICE),
    HISTORICAL_EOD_DATA_DJ(5047, PRICE),
    HISTORICAL_EOD_DATA_SP(5048, PRICE),
    HISTORICAL_EOD_DATA_1Y(2568, FUNCTION),
    HISTORICAL_EOD_DATA_3Y(2569, FUNCTION),
    HISTORICAL_EOD_DATA_5Y(2570, FUNCTION),
    HISTORICAL_EOD_DATA_10Y(2571, FUNCTION),
    HISTORICAL_EOD_DATA_20Y(2572, FUNCTION),
    HISTORICAL_EOD_DATA_30Y(2573, FUNCTION),
    SFDR_CLASSIFICATION_DATA(5884, STATIC),
    HISTORICAL_EOD_DATA_INDICES_SP(5905, PRICE),
    FACTSET_ESTIMATES_INFRONT_ANALYTICS(6096, PRICE),
    FACTSET_ESTIMATES_IEX_MEDIA(6100, PRICE),
    FACTSET_ESTIMATES_ABM_ONLINE_SOLUTIONS(6104, PRICE),
    ESG_SCORE(6117, PRICE),
    ESG_SCORE_DETAIL(6118, PRICE),
    EDI_BOND_REFERENCE_DATA(6120, PRICE),
    INFRONT_SECTOR_CODES(6384, PRICE),
    // extend (ctrl+d and edit) and pay attention to id order
    ;

    private final int id;

    private final Profile.Aspect[] aspects;

    private final String[] pmAbos;

    Selector(int id, Profile.Aspect aspect, String... pmAbos) {
        this.id = id;
        this.aspects = new Profile.Aspect[]{aspect};
        this.pmAbos = pmAbos;
    }

    // TODO: remove use of array if no duplicate selectors are used, current sample is FUNDDATA_FWW/2177 to support migration in permissioning backend
    Selector(int id, Profile.Aspect aspect1, Profile.Aspect aspect2) {
        this.id = id;
        this.aspects = new Profile.Aspect[]{aspect1, aspect2};
        this.pmAbos = new String[0];
    }

    public static Selector valueOf(int id) {
        for (final Selector selector : values()) {
            if (selector.getId() == id) {
                return selector;
            }
        }
        throw new IllegalArgumentException("unknown id: " + id);
    }

    public int getId() {
        return id;
    }

    public Profile.Aspect[] getAspects() {
        return aspects;
    }

    public String[] getPmAbos() {
        return pmAbos;
    }

    public String toString() {
        return name() + "[" + this.id + "/" + Arrays.toString(this.aspects)
                + (this.pmAbos.length == 0 ? "" : "/" + Arrays.toString(this.pmAbos))
                + "]";
    }
}
